name: Run the Python file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #schedule:
  #  - cron: "05 6-18/2 * * *"
  
jobs:
  run:
    name: run
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    permissions:
      contents: write
      id-token: write
      repository-projects: write
      
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: |
       python -VV
       pip install -r requirements.txt
       python oelpreise.py
    # Available enviroment variables
   #   environment: |
    #     LC_ALL: de_DE.UTF-8
    #     LC_TIME: de_DE.UTF-8
    - name: Commit report
      run: |
        git config --global user.name 'axheinz'
        git config --global user.email 'axheinz@gmail.com'
        git add -A
        git commit -am "Automated report"
        git push
